export { hero } from "./hero";
export { servicesHeading, services } from "./services";
export { whyHeading, whyItems } from "./whyChooseUs";
export { testimonialsHeading, testimonials } from "./testimonials";
export { faqHeading, faqs } from "./faq";
export { metrics } from "./metrics";
export { finalCta } from "./finalCta";
export { ticker } from "./ticker";
export { navLinks, navCta } from "./nav";
export { footerContent } from "./footer";
