/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  defaultMetaTitle?: string;
  defaultMetaDescription?: string;
  footerTagline?: string;
  contactEmail?: string;
  contactLocation?: string;
  acknowledgementText?: string;
  navigation?: Array<{
    label?: string;
    href?: string;
    isVisible?: boolean;
    _type: "navLink";
    _key: string;
  }>;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroHeading?: string;
  heroBody?: string;
  heroTrustPoints?: Array<string>;
  officesHeading?: string;
  officesBody?: string;
  officeLocations?: Array<{
    state?: string;
    suburb?: string;
    address?: string;
    phone?: string;
    email?: string;
    _type: "location";
    _key: string;
  }>;
  seoTitle?: string;
  seoDescription?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroHeading?: string;
  heroBody?: string;
  founderSectionHeading?: string;
  founderIntro?: string;
  founderName?: string;
  founderRole?: string;
  founderBio?: string;
  founderPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  missionHeading?: string;
  missionBody?: string;
  valuesHeading?: string;
  valuesItems?: Array<{
    iconName?:
      | "monitor"
      | "users"
      | "file-text"
      | "calendar"
      | "phone-call"
      | "credit-card"
      | "video"
      | "lock"
      | "settings"
      | "link"
      | "bar-chart"
      | "eye"
      | "sliders"
      | "send"
      | "dollar-sign"
      | "alert-circle"
      | "clipboard"
      | "shield-check"
      | "pie-chart"
      | "line-chart"
      | "plug"
      | "activity"
      | "trending-up"
      | "heart"
      | "check-circle"
      | "target"
      | "refresh"
      | "headset"
      | "user-plus"
      | "list-ordered"
      | "moon";
    title?: string;
    body?: string;
    _type: "valueItem";
    _key: string;
  }>;
  teamSectionHeading?: string;
  teamSectionBody?: string;
  credentialsHeading?: string;
  credentialsItems?: Array<string>;
  ctaHeading?: string;
  ctaBody?: string;
  ctaButtonLabel?: string;
  seoTitle?: string;
  seoDescription?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroHeading?: string;
  heroSubheading?: string;
  heroBody?: string;
  heroPrimaryCtaLabel?: string;
  heroSecondaryCtaLabel?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  tickerIntro?: string;
  tickerSpecialties?: Array<string>;
  howItWorksEyebrow?: string;
  howItWorksHeading?: string;
  howItWorksSubheading?: string;
  howItWorksSteps?: Array<{
    stepLabel?: string;
    title?: string;
    description?: string;
    bullets?: Array<string>;
    _type: "step";
    _key: string;
  }>;
  servicesEyebrow?: string;
  servicesTitle?: string;
  servicesBody?: string;
  servicesBridgeText?: string;
  whyHeading?: string;
  whyImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  whyMetrics?: Array<{
    value?: number;
    suffix?: string;
    label?: string;
    _type: "metric";
    _key: string;
  }>;
  whyItems?: Array<{
    iconName?:
      | "monitor"
      | "users"
      | "file-text"
      | "calendar"
      | "phone-call"
      | "credit-card"
      | "video"
      | "lock"
      | "settings"
      | "link"
      | "bar-chart"
      | "eye"
      | "sliders"
      | "send"
      | "dollar-sign"
      | "alert-circle"
      | "clipboard"
      | "shield-check"
      | "pie-chart"
      | "line-chart"
      | "plug"
      | "activity"
      | "trending-up"
      | "heart"
      | "check-circle"
      | "target"
      | "refresh"
      | "headset"
      | "user-plus"
      | "list-ordered"
      | "moon";
    title?: string;
    description?: string;
    _type: "whyItem";
    _key: string;
  }>;
  testimonialsVisible?: boolean;
  testimonialsHeading?: string;
  testimonialsViewMoreLabel?: string;
  finalCtaHeading?: string;
  finalCtaSubheading?: string;
  finalCtaButtonLabel?: string;
  seoTitle?: string;
  seoDescription?: string;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  cardIconName?:
    | "monitor"
    | "users"
    | "file-text"
    | "calendar"
    | "phone-call"
    | "credit-card"
    | "video"
    | "lock"
    | "settings"
    | "link"
    | "bar-chart"
    | "eye"
    | "sliders"
    | "send"
    | "dollar-sign"
    | "alert-circle"
    | "clipboard"
    | "shield-check"
    | "pie-chart"
    | "line-chart"
    | "plug"
    | "activity"
    | "trending-up"
    | "heart"
    | "check-circle"
    | "target"
    | "refresh"
    | "headset"
    | "user-plus"
    | "list-ordered"
    | "moon";
  navDescription?: string;
  navOrder?: number;
  heroLabel?: string;
  heroHeading?: string;
  heroIntro?: string;
  heroCtaLabel?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  featuresHeading?: string;
  featuresIntro?: string;
  features?: Array<{
    iconName?:
      | "monitor"
      | "users"
      | "file-text"
      | "calendar"
      | "phone-call"
      | "credit-card"
      | "video"
      | "lock"
      | "settings"
      | "link"
      | "bar-chart"
      | "eye"
      | "sliders"
      | "send"
      | "dollar-sign"
      | "alert-circle"
      | "clipboard"
      | "shield-check"
      | "pie-chart"
      | "line-chart"
      | "plug"
      | "activity"
      | "trending-up"
      | "heart"
      | "check-circle"
      | "target"
      | "refresh"
      | "headset"
      | "user-plus"
      | "list-ordered"
      | "moon";
    title?: string;
    body?: string;
    _type: "feature";
    _key: string;
  }>;
  ctaHeading?: string;
  ctaBody?: string;
  ctaLabel?: string;
  seoTitle?: string;
  seoDescription?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type FaqItem = {
  _id: string;
  _type: "faqItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: string;
  order?: number;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: string;
  name?: string;
  role?: string;
  order?: number;
};

export type TeamMember = {
  _id: string;
  _type: "teamMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  bio?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  order?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SiteSettings
  | ContactPage
  | SanityImageAssetReference
  | AboutPage
  | SanityImageCrop
  | SanityImageHotspot
  | HomePage
  | Service
  | Slug
  | FaqItem
  | Testimonial
  | TeamMember
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/lib/api/aboutPage.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_type == "aboutPage" && _id == "aboutPage"][0]{    heroHeading,    heroBody,    founderSectionHeading,    founderIntro,    founderName,    founderRole,    founderBio,    founderPhoto { asset->{ _id, url, metadata { lqip, dimensions } }, hotspot, crop, alt },    missionHeading,    missionBody,    valuesHeading,    valuesItems[]{ _key, "icon": iconName, title, body },    teamSectionHeading,    teamSectionBody,    credentialsHeading,    credentialsItems,    ctaHeading,    ctaBody,    ctaButtonLabel,    seoTitle,    seoDescription,  }
export type ABOUT_PAGE_QUERY_RESULT = {
  heroHeading: string | null;
  heroBody: string | null;
  founderSectionHeading: string | null;
  founderIntro: string | null;
  founderName: string | null;
  founderRole: string | null;
  founderBio: string | null;
  founderPhoto: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
  missionHeading: string | null;
  missionBody: string | null;
  valuesHeading: string | null;
  valuesItems: Array<{
    _key: string;
    icon:
      | "activity"
      | "alert-circle"
      | "bar-chart"
      | "calendar"
      | "check-circle"
      | "clipboard"
      | "credit-card"
      | "dollar-sign"
      | "eye"
      | "file-text"
      | "headset"
      | "heart"
      | "line-chart"
      | "link"
      | "list-ordered"
      | "lock"
      | "monitor"
      | "moon"
      | "phone-call"
      | "pie-chart"
      | "plug"
      | "refresh"
      | "send"
      | "settings"
      | "shield-check"
      | "sliders"
      | "target"
      | "trending-up"
      | "user-plus"
      | "users"
      | "video"
      | null;
    title: string | null;
    body: string | null;
  }> | null;
  teamSectionHeading: string | null;
  teamSectionBody: string | null;
  credentialsHeading: string | null;
  credentialsItems: Array<string> | null;
  ctaHeading: string | null;
  ctaBody: string | null;
  ctaButtonLabel: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
} | null;

// Source: src/lib/api/contactPage.ts
// Variable: CONTACT_PAGE_QUERY
// Query: *[_type == "contactPage" && _id == "contactPage"][0]{    heroHeading,    heroBody,    heroTrustPoints,    officesHeading,    officesBody,    officeLocations[]{ _key, state, suburb, address, phone, email },    seoTitle,    seoDescription,  }
export type CONTACT_PAGE_QUERY_RESULT = {
  heroHeading: string | null;
  heroBody: string | null;
  heroTrustPoints: Array<string> | null;
  officesHeading: string | null;
  officesBody: string | null;
  officeLocations: Array<{
    _key: string;
    state: string | null;
    suburb: string | null;
    address: string | null;
    phone: string | null;
    email: string | null;
  }> | null;
  seoTitle: string | null;
  seoDescription: string | null;
} | null;

// Source: src/lib/api/faq.ts
// Variable: FAQ_QUERY
// Query: *[_type == "faqItem"] | order(order asc){    _id,    question,    answer,    order,  }
export type FAQ_QUERY_RESULT = Array<{
  _id: string;
  question: string | null;
  answer: string | null;
  order: number | null;
}>;

// Source: src/lib/api/homePage.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "homePage" && _id == "homePage"][0]{    heroHeading,    heroSubheading,    heroBody,    heroPrimaryCtaLabel,    heroSecondaryCtaLabel,    heroImage { asset->{ _id, url, metadata { lqip, dimensions } }, hotspot, crop, alt },    tickerIntro,    tickerSpecialties,    howItWorksEyebrow,    howItWorksHeading,    howItWorksSubheading,    howItWorksSteps[]{ _key, stepLabel, title, description, bullets },    servicesEyebrow,    servicesTitle,    servicesBody,    servicesBridgeText,    whyHeading,    whyImage { asset->{ _id, url, metadata { lqip, dimensions } }, hotspot, crop, alt },    whyMetrics[]{ _key, value, suffix, label },    whyItems[]{ _key, iconName, title, description },    testimonialsVisible,    testimonialsHeading,    testimonialsViewMoreLabel,    finalCtaHeading,    finalCtaSubheading,    finalCtaButtonLabel,    seoTitle,    seoDescription,  }
export type HOME_PAGE_QUERY_RESULT = {
  heroHeading: string | null;
  heroSubheading: string | null;
  heroBody: string | null;
  heroPrimaryCtaLabel: string | null;
  heroSecondaryCtaLabel: string | null;
  heroImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
  tickerIntro: string | null;
  tickerSpecialties: Array<string> | null;
  howItWorksEyebrow: string | null;
  howItWorksHeading: string | null;
  howItWorksSubheading: string | null;
  howItWorksSteps: Array<{
    _key: string;
    stepLabel: string | null;
    title: string | null;
    description: string | null;
    bullets: Array<string> | null;
  }> | null;
  servicesEyebrow: string | null;
  servicesTitle: string | null;
  servicesBody: string | null;
  servicesBridgeText: string | null;
  whyHeading: string | null;
  whyImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
  whyMetrics: Array<{
    _key: string;
    value: number | null;
    suffix: string | null;
    label: string | null;
  }> | null;
  whyItems: Array<{
    _key: string;
    iconName:
      | "activity"
      | "alert-circle"
      | "bar-chart"
      | "calendar"
      | "check-circle"
      | "clipboard"
      | "credit-card"
      | "dollar-sign"
      | "eye"
      | "file-text"
      | "headset"
      | "heart"
      | "line-chart"
      | "link"
      | "list-ordered"
      | "lock"
      | "monitor"
      | "moon"
      | "phone-call"
      | "pie-chart"
      | "plug"
      | "refresh"
      | "send"
      | "settings"
      | "shield-check"
      | "sliders"
      | "target"
      | "trending-up"
      | "user-plus"
      | "users"
      | "video"
      | null;
    title: string | null;
    description: string | null;
  }> | null;
  testimonialsVisible: boolean | null;
  testimonialsHeading: string | null;
  testimonialsViewMoreLabel: string | null;
  finalCtaHeading: string | null;
  finalCtaSubheading: string | null;
  finalCtaButtonLabel: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
} | null;

// Source: src/lib/api/services.ts
// Variable: SERVICES_QUERY
// Query: *[_type == "service"] | order(navOrder asc){    _id,    title,    "slug": slug.current,    "href": "/services/" + slug.current,    description,    cardIconName,    navDescription,    navOrder,  }
export type SERVICES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  href: string | null;
  description: string | null;
  cardIconName:
    | "activity"
    | "alert-circle"
    | "bar-chart"
    | "calendar"
    | "check-circle"
    | "clipboard"
    | "credit-card"
    | "dollar-sign"
    | "eye"
    | "file-text"
    | "headset"
    | "heart"
    | "line-chart"
    | "link"
    | "list-ordered"
    | "lock"
    | "monitor"
    | "moon"
    | "phone-call"
    | "pie-chart"
    | "plug"
    | "refresh"
    | "send"
    | "settings"
    | "shield-check"
    | "sliders"
    | "target"
    | "trending-up"
    | "user-plus"
    | "users"
    | "video"
    | null;
  navDescription: string | null;
  navOrder: number | null;
}>;

// Source: src/lib/api/services.ts
// Variable: SERVICE_BY_SLUG_QUERY
// Query: *[_type == "service" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    heroLabel,    heroHeading,    heroIntro,    heroCtaLabel,    heroImage { asset->{ _id, url, metadata { lqip, dimensions } }, hotspot, crop, alt },    featuresHeading,    featuresIntro,    features[]{ _key, iconName, title, body },    ctaHeading,    ctaBody,    ctaLabel,    seoTitle,    seoDescription,  }
export type SERVICE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  heroLabel: string | null;
  heroHeading: string | null;
  heroIntro: string | null;
  heroCtaLabel: string | null;
  heroImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
  featuresHeading: string | null;
  featuresIntro: string | null;
  features: Array<{
    _key: string;
    iconName:
      | "activity"
      | "alert-circle"
      | "bar-chart"
      | "calendar"
      | "check-circle"
      | "clipboard"
      | "credit-card"
      | "dollar-sign"
      | "eye"
      | "file-text"
      | "headset"
      | "heart"
      | "line-chart"
      | "link"
      | "list-ordered"
      | "lock"
      | "monitor"
      | "moon"
      | "phone-call"
      | "pie-chart"
      | "plug"
      | "refresh"
      | "send"
      | "settings"
      | "shield-check"
      | "sliders"
      | "target"
      | "trending-up"
      | "user-plus"
      | "users"
      | "video"
      | null;
    title: string | null;
    body: string | null;
  }> | null;
  ctaHeading: string | null;
  ctaBody: string | null;
  ctaLabel: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
} | null;

// Source: src/lib/api/services.ts
// Variable: SERVICE_SLUGS_QUERY
// Query: *[_type == "service"]{ "slug": slug.current }
export type SERVICE_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/lib/api/siteSettings.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]{    defaultMetaTitle,    defaultMetaDescription,    footerTagline,    contactEmail,    contactLocation,    acknowledgementText,    navigation[]{ _key, label, href, isVisible },  }
export type SITE_SETTINGS_QUERY_RESULT = {
  defaultMetaTitle: string | null;
  defaultMetaDescription: string | null;
  footerTagline: string | null;
  contactEmail: string | null;
  contactLocation: string | null;
  acknowledgementText: string | null;
  navigation: Array<{
    _key: string;
    label: string | null;
    href: string | null;
    isVisible: boolean | null;
  }> | null;
} | null;

// Source: src/lib/api/team.ts
// Variable: TEAM_QUERY
// Query: *[_type == "teamMember"] | order(order asc){    _id,    name,    role,    bio,    photo { asset->{ _id, url, metadata { lqip, dimensions } }, hotspot, crop, alt },    order,  }
export type TEAM_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  role: string | null;
  bio: string | null;
  photo: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
  order: number | null;
}>;

// Source: src/lib/api/testimonials.ts
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial"] | order(order asc){    _id,    quote,    name,    role,    order,  }
export type TESTIMONIALS_QUERY_RESULT = Array<{
  _id: string;
  quote: string | null;
  name: string | null;
  role: string | null;
  order: number | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "aboutPage" && _id == "aboutPage"][0]{\n    heroHeading,\n    heroBody,\n    founderSectionHeading,\n    founderIntro,\n    founderName,\n    founderRole,\n    founderBio,\n    founderPhoto { asset->{ _id, url, metadata { lqip, dimensions } }, hotspot, crop, alt },\n    missionHeading,\n    missionBody,\n    valuesHeading,\n    valuesItems[]{ _key, "icon": iconName, title, body },\n    teamSectionHeading,\n    teamSectionBody,\n    credentialsHeading,\n    credentialsItems,\n    ctaHeading,\n    ctaBody,\n    ctaButtonLabel,\n    seoTitle,\n    seoDescription,\n  }\n': ABOUT_PAGE_QUERY_RESULT;
    '\n  *[_type == "contactPage" && _id == "contactPage"][0]{\n    heroHeading,\n    heroBody,\n    heroTrustPoints,\n    officesHeading,\n    officesBody,\n    officeLocations[]{ _key, state, suburb, address, phone, email },\n    seoTitle,\n    seoDescription,\n  }\n': CONTACT_PAGE_QUERY_RESULT;
    '\n  *[_type == "faqItem"] | order(order asc){\n    _id,\n    question,\n    answer,\n    order,\n  }\n': FAQ_QUERY_RESULT;
    '\n  *[_type == "homePage" && _id == "homePage"][0]{\n    heroHeading,\n    heroSubheading,\n    heroBody,\n    heroPrimaryCtaLabel,\n    heroSecondaryCtaLabel,\n    heroImage { asset->{ _id, url, metadata { lqip, dimensions } }, hotspot, crop, alt },\n    tickerIntro,\n    tickerSpecialties,\n    howItWorksEyebrow,\n    howItWorksHeading,\n    howItWorksSubheading,\n    howItWorksSteps[]{ _key, stepLabel, title, description, bullets },\n    servicesEyebrow,\n    servicesTitle,\n    servicesBody,\n    servicesBridgeText,\n    whyHeading,\n    whyImage { asset->{ _id, url, metadata { lqip, dimensions } }, hotspot, crop, alt },\n    whyMetrics[]{ _key, value, suffix, label },\n    whyItems[]{ _key, iconName, title, description },\n    testimonialsVisible,\n    testimonialsHeading,\n    testimonialsViewMoreLabel,\n    finalCtaHeading,\n    finalCtaSubheading,\n    finalCtaButtonLabel,\n    seoTitle,\n    seoDescription,\n  }\n': HOME_PAGE_QUERY_RESULT;
    '\n  *[_type == "service"] | order(navOrder asc){\n    _id,\n    title,\n    "slug": slug.current,\n    "href": "/services/" + slug.current,\n    description,\n    cardIconName,\n    navDescription,\n    navOrder,\n  }\n': SERVICES_QUERY_RESULT;
    '\n  *[_type == "service" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    heroLabel,\n    heroHeading,\n    heroIntro,\n    heroCtaLabel,\n    heroImage { asset->{ _id, url, metadata { lqip, dimensions } }, hotspot, crop, alt },\n    featuresHeading,\n    featuresIntro,\n    features[]{ _key, iconName, title, body },\n    ctaHeading,\n    ctaBody,\n    ctaLabel,\n    seoTitle,\n    seoDescription,\n  }\n': SERVICE_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "service"]{ "slug": slug.current }\n': SERVICE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "siteSettings" && _id == "siteSettings"][0]{\n    defaultMetaTitle,\n    defaultMetaDescription,\n    footerTagline,\n    contactEmail,\n    contactLocation,\n    acknowledgementText,\n    navigation[]{ _key, label, href, isVisible },\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "teamMember"] | order(order asc){\n    _id,\n    name,\n    role,\n    bio,\n    photo { asset->{ _id, url, metadata { lqip, dimensions } }, hotspot, crop, alt },\n    order,\n  }\n': TEAM_QUERY_RESULT;
    '\n  *[_type == "testimonial"] | order(order asc){\n    _id,\n    quote,\n    name,\n    role,\n    order,\n  }\n': TESTIMONIALS_QUERY_RESULT;
  }
}
